name: Prevent unauthorized branch creation

on:
  create:
    ref_type: branch

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    if: github.repository_owner != 'michaelthomasletts' 
    steps:
    - name: Delete Unauthorized Branch
      run: |
        git push origin --delete "${{ github.ref }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
